var WIDTH=screen.availWidth;var HEIGHT=screen.availWidth;var canvas;var con;var g;var pxs=new Array();var rint=50;$(document).ready(function(){canvas=document.getElementById("pixie");$(canvas).attr("width",WIDTH).attr("height",HEIGHT);con=canvas.getContext("2d");for(var a=0;a<50;a++){pxs[a]=new Circle();pxs[a].reset()}
setInterval(draw,rint);});function draw(){con.clearRect(0,0,WIDTH,HEIGHT);for(var a=0;a<pxs.length;a++){pxs[a].fade();pxs[a].move();pxs[a].draw()}}
function Circle(){this.s={ttl:8000,xmax:5,ymax:2,rmax:10,rt:1,xdef:960,ydef:540,xdrift:4,ydrift:4,random:true,blink:true};this.reset=function(){this.x=(this.s.random?WIDTH*Math.random():this.s.xdef);this.y=(this.s.random?HEIGHT*Math.random():this.s.ydef);this.r=((this.s.rmax-1)*Math.random())+1;this.dx=(Math.random()*this.s.xmax)*(Math.random()<0.5?-1:1);this.dy=(Math.random()*this.s.ymax)*(Math.random()<0.5?-1:1);this.hl=(this.s.ttl/rint)*(this.r/this.s.rmax);this.rt=Math.random()*this.hl;this.s.rt=Math.random()+1;this.stop=Math.random()*0.2+0.4;this.s.xdrift*=Math.random()*(Math.random()<0.5?-1:1);this.s.ydrift*=Math.random()*(Math.random()<0.5?-1:1)};this.fade=function(){this.rt+=this.s.rt};this.draw=function(){if(this.s.blink&&(this.rt<=0||this.rt>=this.hl)){this.s.rt=this.s.rt*-1}else{if(this.rt>=this.hl){this.reset()}}
var b=1-(this.rt/this.hl);con.beginPath();con.arc(this.x,this.y,this.r,0,Math.PI*2,true);con.closePath();var a=this.r*b;g=con.createRadialGradient(this.x,this.y,0,this.x,this.y,(a<=0?1:a));g.addColorStop(0,"rgba(238,180,28,"+b+")");g.addColorStop(this.stop,"rgba(238,180,28,"+(b*0.2)+")");g.addColorStop(1,"rgba(238,180,28,0)");con.fillStyle=g;con.fill()};this.move=function(){this.x+=(this.rt/this.hl)*this.dx;this.y+=(this.rt/this.hl)*this.dy;if(this.x>WIDTH||this.x<0){this.dx*=-1}
if(this.y>HEIGHT||this.y<0){this.dy*=-1}};this.getX=function(){return this.x};this.getY=function(){return this.y}};var dropBanner=false,imgs=$("#gallery .img").length,ind=null;$(".btn").click(function(){var $elem=$(this),opens=$(`#${$(this).attr("opens")}`);if($elem.hasClass("selected")){return;}else{$(".btn").removeClass("selected");$elem.addClass("selected");$(".banner:not(#ooc) .scroller").fadeOut(200);setTimeout(()=>{opens.fadeIn(200);},200);}});$("#rope").click(function(){var $elem=$(this);$elem.animate({top:"0vh"},200);setTimeout(()=>{$elem.animate({top:"-20vh"})},200);if(!dropBanner){$("#ooc").removeAttr("style");$("#ooc").show();dropBanner=true;}else if(dropBanner&&$("#ooc").is(":visible")){$("#ooc").animate({top:"-95vh"},500);setTimeout(()=>{$("#ooc").removeAttr("style");},500);dropBanner=false;}else if(dropBanner&&$("#gallBanner").is(":visible")){$("#gallBanner").animate({top:"-95vh"},500);setTimeout(()=>{$("#gallBanner").remove();},500);dropBanner=false;}else{}});$(".friend").each(function(){var $elem=$(this),face=$elem.attr("img"),name=$elem.attr("name"),desc=$elem.attr("desc"),link=$elem.attr("profile"),friends=$("#friends .friends");if(!face){face="https://i.imgur.com/pfAXDsH.jpg";};if(!link){link="#";};if(!name){name="";};if(!desc){desc="";};$("<div>",{class:"friendCard"}).appendTo(friends);$("<a>",{class:"friendFace",target:"_blank",href:link,rel:"noopener noreferrer",style:`background-image:url(${face})`}).appendTo(".friendCard:last-child");$("<div>",{class:"friendContent"}).appendTo(".friendCard:last-child");$("<div>",{class:"friendName",html:name}).appendTo(".friendCard:last-child .friendContent");$("<div>",{class:"friendDesc"}).appendTo(".friendCard:last-child .friendContent");$("<div>",{class:"friendScroll",html:desc}).appendTo(".friendCard:last-child .friendDesc");$("<hr>").appendTo(container);$elem.remove();});$(".img").each(function(){var img=$(this).attr("img");if(!img){img="https://i.imgur.com/pfAXDsH.jpg";}
$(this).css("background-image",`url(${img})`);});$(".img").click(function(){var img=$(this).attr("img");ind=$(this).index();if(!img){img="https://i.imgur.com/pfAXDsH.jpg";}
$("<div>",{class:"banner dropBanner",id:"gallBanner"}).insertBefore("#rope");$("<div>",{class:"content"}).appendTo("#gallBanner");$("<img>",{src:img}).appendTo("#gallBanner .content");$("<div>",{class:"navi"}).appendTo("#gallBanner");$("<div>",{class:"nav prev",click:function(){var nextImg=null;if(ind==0){ind=imgs-1;}else{--ind;}
nextImg=$("#gallery .img").eq(ind).attr("img");if(!nextImg){nextImg="https://i.imgur.com/pfAXDsH.jpg";}
$("#gallBanner img").attr("src",nextImg);}}).appendTo("#gallBanner .navi");$("<div>",{class:"nav next",click:function(){var nextImg=null;if(ind==imgs-1){ind=0;}else{++ind;}
nextImg=$("#gallery .img").eq(ind).attr("img");if(!nextImg){nextImg="https://i.imgur.com/pfAXDsH.jpg";}
$("#gallBanner img").attr("src",nextImg);}}).appendTo("#gallBanner .navi");setTimeout(()=>{$("#gallBanner").show();dropBanner=true;},100);});