var orientation,images=$(".img").length,curIndex,insert=function insert(main_string,ins_string,pos){if(typeof(pos)=="undefined"){pos=0;}
if(typeof(ins_string)=="undefined"){ins_string='';}
return main_string.slice(0,pos)+ins_string+main_string.slice(pos);};$(window).on("orientationchange",function(e){orientation=e.orientation;var findBox,boxColor;if($("body").find(".box").length>0){findBox=true;boxColor=$(".box").hasClass("white")?"white":"black";}
if(orientation=="portrait"&&findBox){$(".box").css({"top":`${boxColor=="white"?"56.5vh":"2vh"}`,"left":`${boxColor=="white"?"5vw":"11.5vw"}`,"height":"42vh","width":"83vw"})}else if(orientation=="landscape"&&findBox){$(".box").css({"top":"12.5vh","left":`${boxColor=="white"?"35vw":"5vw"}`,"height":"75vh","width":"60vw"})}});$(window).orientationchange();$(".color").css("color",$(".color").html());function removeBox(){$(".tab").removeClass("selected");$(".box").addClass("delete").fadeOut(200);setTimeout(function(){$(".box.delete").remove();},200);}
$(".img").each(function(){var img=$(this).attr("img");if(!img){$(this).attr("img","https://i.imgur.com/oO7FwYp.jpg");img="https://i.imgur.com/oO7FwYp.jpg";}
$(this).css("background-image",`url(${img})`);$(this).attr("onmouseenter","shroudImage()");$(this).attr("onmouseleave","colorImage()");$(this).attr("onclick","showGallery()");});$(".friendImage").each(function(){var img=$(this).attr("img");if(!img){$(this).attr("img","https://i.imgur.com/oO7FwYp.jpg");img="https://i.imgur.com/oO7FwYp.jpg";}
$(this).css("background-image",`url(${img})`);})
function shroudImage(){$(".img").css("filter","grayscale(100%)");$(".img:hover").css("filter","none");};function colorImage(){$(".img").css("filter","none");};function changePicture(ind){var newImage=$(".img").eq(ind).attr("img");$("#gallOverlay img").replaceWith(function(){return $("<img>",{src:newImage})});}
function showGallery(){var $elem=$(".img:hover"),image=$elem.attr("img");curIndex=$elem.index();$("<div>",{id:"gallOverlay"}).appendTo("body");$("<div>",{class:"flexBox"}).appendTo("#gallOverlay");$("<div>",{id:"gallExit",click:function(){$("#gallOverlay").fadeOut(200);setTimeout(function(){$("#gallOverlay").remove();},200);}}).appendTo("#gallOverlay .flexBox");$("<div>",{class:"prev",click:function(){if(curIndex==0){curIndex=images-1;}else{--curIndex;}
changePicture(curIndex)}}).appendTo("#gallOverlay .flexBox");$("<img>",{src:image}).appendTo("#gallOverlay .flexBox");$("<div>",{class:"next",click:function(){if(curIndex==images-1){curIndex=0;}else{++curIndex}
changePicture(curIndex);}}).appendTo("#gallOverlay .flexBox")}
$(".tab").click(function(){var height=$(this).outerHeight(),top=$(this).offset().top,left=$(this).offset().left,color=$(this).parent().hasClass("white")?"white":"black",style=`top:${top}px;left:${left}px;height:${height}px;`,opens=`#${$(this).attr("opens")}`;removeBox();$(this).addClass("selected");$("<div>",{class:`box ${color}`,style:style}).appendTo("body");$("<div>",{class:"scrollerWrap"}).appendTo(".box");$("<div>",{class:"scroller",html:$(opens).html()}).appendTo(".box .scrollerWrap");$("#ooc").fadeOut(200);$(`.box.${color}`).animate({"top":`${orientation=="landscape"?"12.5vh":color=="white"?"56.5vh":"2vh"}`,"height":`${orientation=="landscape"?"75vh":"42vh"}`},500);setTimeout(function(){$(`.box.${color}`).animate({"width":`${orientation=="landscape"?"60vw":"83vw"}`,"left":`${color=="white"?orientation=="landscape"?"35vw":"5vw":orientation=="landscape"?"5vw":"11.5vw"}`},500);if(color=="white"){$("#darkTop").css("-webkit-mask-position","left, 100vw");$("#rift").css("-webkit-mask-position","84.6vw");}else if(color=="black"){$("#darkTop").css("-webkit-mask-position",`${orientation=="landscape"?"-200vw, -100vw":"-200vw, -200vw"}`);$("#rift").css("-webkit-mask-position",`${orientation=="landscape"?"-84.6vw":"-184.6vw -18vw"}`)}},500);setTimeout(()=>{$(".box .scroller").animate({"opacity":"1"},500);setTimeout(()=>{$(".box .scroller").css("pointer-events","all");},500);},1000);});$(".box.black").scroll(function(){console.log($(this).scrollTop())});$("#reset").click(()=>{removeBox();$("#ooc").fadeIn(200);$("#darkTop, #rift").removeAttr("style");})