var curIndex,images=$(".picture").length;function changePicture(ind){var img=$(".picture").eq(ind).attr("img");if(!img){img="https://i.imgur.com/usH1KbX.png";}
$("#gallOverlay img").replaceWith($("<img>",{src:img}));}
$("body").append($("<div>",{id:"tooltips"}));$(".tooltip").hover(function(){var position=$(this).offset(),height=$(this).outerHeight();width=$(this).outerWidth(),opens=`#${$(this).attr("opens")}`;$(".tip").animate({"opacity":"0","margin-top":`-${height*2}px`},300)
setTimeout(()=>{$(".tip").remove();$("<div>",{class:"tip hovered",style:`top:${position.top}px;left:${position.left+(width/2)}px`,}).appendTo("#tooltips")
$("<div>",{class:"tipHolder"}).appendTo("#tooltips .tip");$("<div>",{class:"tipScrollWrap",}).appendTo("#tooltips .tip .tipHolder");$("<div>",{class:"tipScroller",html:$(opens).find(".scroller").html(),}).appendTo("#tooltips .tip .tipScrollWrap");},300);},function(){var height=$(this).outerHeight();$(`.tip`).animate({"opacity":"0","margin-top":`-${height*2}px`},300)
setTimeout(()=>{$(`.tip`).remove();},300);});$(".tooltip").click(function(){var opens=`#${$(this).attr("opens")}`;if($(opens).is(":visible")){return;}
$(`.tip`).animate({"opacity":"0","margin-top":`-${$(this).outerHeight()*2}px`},300)
setTimeout(()=>{$(`.tip`).remove();},300);$(".tooltip").removeClass("clicked");$(this).addClass("clicked");$(".tab.visible").animate({"height":"0","opacity":"0"},500,()=>{$(".tab.visible").hide();$(".tab.visible").removeClass("visible");})
setTimeout(()=>{$(opens).show();$(opens).animate({"height":"100%","opacity":"1"},500,()=>{$(opens).addClass("visible");})},500);});$(".picture").each(function(){var image=$(this).attr("img");if(!image){image="https://i.imgur.com/usH1KbX.png";$(this).css("border-color","transparent");}
$(this).css("background-image",`url(${image})`);});$(".picture").hover(function(){$(".picture").css({"filter":"grayscale(100%)"});$(this).css({"filter":"grayscale(0)","transform":"scale(1.1)"});},function(){$(".picture").css({"filter":"none","transform":"none"});})
$(".picture").click(function(){var width=$(".flexBox").outerWidth(),img=$(this).attr("img");if(!img){img="https://i.imgur.com/usH1KbX.png";}
curIndex=$(this).index();$(".flexBox").animate({"margin-left":`-${width/2}px`,"opacity":"0"},300,()=>{$(".flexBox").css("pointer-events","none");});$("<div>",{id:"gallOverlay",}).insertBefore("#tooltips");$("<div>",{id:"gallExit",click:function(){$("#gallOverlay").animate({"margin-left":"22.5vw","opacity":"0"},300,()=>{$("#gallOverlay").remove();});$(".flexBox").animate({"margin-left":"0","opacity":"1"},300,()=>{$(".flexBox").css("pointer-events","all");});}}).appendTo("#gallOverlay");$("<div>",{class:"btn prev",click:function(){if(curIndex==0){curIndex=images-1}else{--curIndex}
changePicture(curIndex);}}).appendTo("#gallOverlay");$("<img>",{src:img}).appendTo("#gallOverlay");$("<div>",{class:"btn next",click:function(){if(curIndex==images-1){curIndex=0}else{++curIndex}
changePicture(curIndex);}}).appendTo("#gallOverlay");$("#gallOverlay").animate({"margin-left":"0","opacity":1},300);});